language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
jdk: oraclejdk8
before_install:
  - chmod +x mvnw

deploy:
  provider: script
  
  script:
  - jdk_switcher use oraclejdk8
  - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true
  skip_cleanup: true
  on:
    tags: true
