spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://119.29.229.56:8081/health_diet?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: health
        password: /F9D%<Y-V{]Zv)~q
#    h2:
#      console:
#        enabled: true
#        path: /h2
#        settings:
#          web-allow-others: true
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: org.h2.Driver
#        url: jdbc:h2:file:~/test
#        username: sa
#        password: 1234564
#    redis:
#         database: 0
#         host: 127.0.0.1
#         port: 6379
#         password: # 密码（默认为空）
