spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:~/test
        username: martinho0330@gmail.com
        password: Who-the-hello-can-break-this!
    h2:
      console:
        enabled: true
        path: /h2
        settings:
          web-allow-others: true
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/health_diet?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&sessionVariables=group_concat_max_len=204800
#        username: root
#        password: 123456
#    redis:
#         database: 0
#         host: 127.0.0.1
#         port: 6379
#         password: # 密码（默认为空）
